#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_credentials: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
#        allow_headers: ['Content-Type', 'Authorization']
#        expose_headers: ['Link']
#        max_age: 3600
#    paths:
#        '^/api/':
#            allow_origin: [ '^http://localhost:5173' ]
#            allow_headers: [ 'Content-Type', 'Authorization', 'X-Custom-Auth', 'X-Requested-With', 'Origin', 'Accept' ]
#            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
#            allow_credentials: true
#            max_age: 3600
#        '^/':
#            origin_regex: true
#            allow_origin: [ '^http://localhost:[0-9]+' ]
#            allow_headers: [ 'X-Custom-Auth' ]
#            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
#            max_age: 3600
#            hosts: [ '^api\.' ]
#
