twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_horizontal_layout.html.twig' ]
    globals:
        avatars_directory: 'uploads/avatars/'
#    paths:
#        '%kernel.project_dir%/vendor/blackknight467/star-rating-bundle/blackknight467/StarRatingBundle/Resources/views': BrokoskokoliStarRatingBundle

when@test:
    twig:
        strict_variables: true
